### PR TITLE
Update node and audit fix easy audit-fix-ables

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Review by katjam — APPROVED** [review]
This is OK with me. I usually track one version behind the latest LTS - so would be 16 now because stuff is sometimes slow to update on 3rd party servers etc. node changes so frequently.

I also usually fix to a major version to automatically get security patches and minors.

Having said that. I approve if you want to do it this way.

**Comment by aaaaargZombies** [comment]
just a note that I don't think elm language server runs on node >16 maybe it's possible to run the lsp on a different version of node while using the project so it's not an issue?

**Comment by katjam** [comment]
I usually run at least one LTS behind latest for node because it takes build servers and tooling ages to catch up. Lots of my projects are still on 14 and if I started a new one today, I'd use 16, not 18.

**Comment by katjam** [comment]
Closing in favour of sticking with 16 for a bit.

**Pull request closed without merging**
