### PR TITLE
Improve logo markup

### PR DESCRIPTION
**Pull request by erbridge**
- Use alt text instead of complex hidden images and visibly hidden spans.
- Drop the invisible and confusing link to the home page. We already have a link to take us home in the header, and this one had no indication it was a link and a very wide catchment area for that link.

This change brought to you by me scrolling to the top of the page and clicking somewhere on the background and being navigated somewhere very unexpectedly.

### CODE REVIEW

**Comment by katjam** [comment]
I'm happy with this - especially the use of alt text for description - but it is a little in conflict with #359 which indicates that we prefer the logo to link to home.

As with other "fixes" - was this raised as an issue or just something you decided to do? I'm still concerned that we should not be doing ad-hoc unplanned work.

**Comment by katjam** [comment]
@kimadactyl I think you may have been the one to raise the logo not linking on mobile. In light of that, are you happy for this to be merged?

**Comment by kimadactyl** [comment]
Build currently failing so can't review but I'm sure it's fine no need to get signoff from me :)

**Comment by katjam** [comment]
In that case I guess I will mark #359 as closed by this also.

**Review by katjam — APPROVED** [review]
Let's merge.

**Pull request merged**
