### PR TITLE
Clean up unused code, comments, etc

### PR DESCRIPTION
**Pull request by erbridge**
## Description

The commits explain themselves.

### CODE REVIEW

**Comment by katjam** [comment]
@erbridge did you use Elm tooling for this? Or should we action that after? 

See this closed issue - we decided not to prioritise code linting integration for this project.
https://github.com/GenderedIntelligence/the-trans-dimension/issues/78

**Comment by erbridge** [comment]
I used my editor integration to highlight them with a manual review (which I was doing anyway to spot any outstanding issues).

**Comment by erbridge** [comment]
Nice to know there are tools for this :)

**Review by katjam — APPROVED** [review]
I'm happy with this if you are happy with this @erbridge

**Comment by katjam** [comment]
@erbridge I'm going to go ahead and fix the conflict and merge in the interests of time since you're not back til Weds.

**Comment by erbridge** [comment]
It doesn't feel urgent @katjam. I'm happy to resolve it on Wednesday.

**Comment by erbridge** [comment]
Feel free to merge if you're done, though :)

**Comment by katjam** [comment]
We're planning to go live on Weds. #354

**Pull request merged**
