### PR TITLE
Strip out the beta banner code

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Review by aaaaargZombies — APPROVED** [review]
working for me, will need to login and update the cloudflare variables after this has merged.

**Comment by katjam** [comment]
Curious. Why did we first make this configurable and then strip out altogether?

Also - I kind of think we are still in Beta... we've never tested in outside of one very short conversational session with partners. Maybe the Beta status is meaningless, but I'd like it to be clear to users that this is a work in progress and that we are open to feedback.

@kimadactyl I guess this is your call - or @GeorgieMcVicar 's ... apologies if I missed a conversation.

**Comment by kimadactyl** [comment]
I think it wasn't working properly

> Also - I kind of think we are still in Beta

Agree - this was taken out because Ivan found it was hard blocking access for screen readers. On the fence if it should be there or not but we didn't have time to fix it before launch.

**Comment by katjam** [comment]
OK. let's leave it and make an issue if it is decided that we want to make people explicitly aware that we are work in progress.

**Pull request merged**
