### PR TITLE
add aria-label to the footer link for GI for screen readers

### LINKED ISSUE #340: No content in footer 'Gendered Intelligence' logo link

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Fixes #340

## Description

- add text content to the `a` tag as it only has a background image set.
- the text is set to be transparent so as not to create visual regression, I hope this is sufficient.

for the confusing diffs I'm exporting `transparent` on `Global.elm:1` and `rgba` on `Global.elm:4`

### CODE REVIEW

**Comment by ivan-kocienski-gfsc** [comment]
Hmm could this be done by putting the text into a `span` tag and setting `display: none`? i think that is the done thing in these situations. According to [this random blog i found](https://amberwilson.co.uk/blog/are-your-anchor-links-accessible/) we should be using aria labels, so that may be worth trying out. (i think we use aria stuff elsewhere in the code that may provide a template solution)

**Comment by aaaaargZombies** [comment]
playing around with the accessibility dev tools and reading that article it seems that for links at least aria-label is the way to go

I also found this which is a good example of it in action https://daverupert.com/2021/01/art-direction-for-static-sites/

**Comment by katjam** [comment]
Absolute position off-screen 
https://webaim.org/techniques/css/invisiblecontent/#techniques

or

aria-label 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

depending on your use case.

**Review by katjam — APPROVED** [review]
Great!

**Pull request merged**
